import type { Foundation, GridMm, ModuleType, OpeningType } from './config.js';
import type { I18nText } from './i18n.js';
import type { RuleDef } from './rules.js';
import type { Czk, Kg, Kw, M3, Mm, Ratio, SkuRef, Vec3 } from './units.js';

/**
 * Tenant catalog = every domain number (dimensions, masses, clearances,
 * limits, rates). Code never hard-codes a domain value. Versioned and
 * immutable once a config references it.
 */

/** Provenance of a value; required for anything not obvious. */
export interface Source {
  /** e.g. "EN 10219-2 tab. B.1", "manuál výrobce kamen", "interní standard". */
  ref: string;
  /** true = unverified placeholder; shown as a warning in admin and tech PDF. */
  placeholder?: boolean;
}

/** A domain number together with its source. */
export interface Sourced<T = number> {
  value: T;
  source: Source;
}

interface ItemBase {
  sku: SkuRef;
  name: I18nText;
  active: boolean;
  source?: Source;
}

// ------------------------------------------------------------ materials ---

/** Structural steel grade. */
export interface SteelMaterial extends ItemBase {
  kind: 'steel';
  grade: string; // 'S235JRH', 'S355J2H'
  density_kg_m3: number;
  /** Material purchase price per kg. */
  cost_per_kg: Czk;
  /** Surface treatment price per m² (painting / galvanising). */
  coating_cost_per_m2: Czk;
  coating: string; // e.g. 'žárový zinek + PU'
}

export type ProfileShape =
  | { shape: 'RHS'; h: Mm; b: Mm; t: Mm }
  | { shape: 'U'; h: Mm; b: Mm; tw: Mm; tf: Mm }
  | { shape: 'L'; a: Mm; b: Mm; t: Mm };

export interface SteelProfile extends ItemBase {
  kind: 'steel_profile';
  /** Steel material SKU. */
  material: SkuRef;
  /** Designation for BOM, e.g. 'RHS 100×100×4'. */
  designation: string;
  section: ProfileShape;
  /** Nominal mass per metre (from standard table, not computed). */
  mass_kg_per_m: Kg;
  /** Outer surface per metre for coating [m²/m]. */
  surface_m2_per_m: number;
  waste: Ratio;
}

/** Sawn / planed timber sold by the metre (battens, studs, bench supports). */
export interface TimberSection extends ItemBase {
  kind: 'timber';
  species: string;
  /** Section b × h [mm]. */
  b_mm: Mm;
  h_mm: Mm;
  density_kg_m3: number;
  cost_per_m: Czk;
  waste: Ratio;
}

export type PanelRole =
  | 'exterior_cladding'
  | 'roof_covering'
  | 'interior_cladding'
  | 'insulation'
  | 'membrane'
  | 'vapour_barrier'
  | 'sheathing'
  | 'floor'
  | 'bench_board'
  | 'decking';

/** Anything sold by area (cladding, insulation, membranes, boards). */
export interface PanelMaterial extends ItemBase {
  kind: 'panel';
  role: PanelRole;
  material: string;
  thickness_mm: Mm;
  mass_kg_per_m2: Kg;
  cost_per_m2: Czk;
  /** Installation labour [h/m²]. */
  install_h_per_m2: number;
  waste: Ratio;
  combustible: boolean;
  /** Board geometry for instanced lamellas (omitted for sheets / rolls). */
  board?: { width_mm: Mm; coverWidth_mm: Mm };
  /** Viewer material id (PBR set). */
  appearance: string;
}

// -------------------------------------------------------------- layups ---

/** Placeholder tokens replaced by the config's choice at evaluation time. */
export type LayupSkuToken = '$exterior' | '$roof' | '$interior';

/** One layer of a build-up, listed from outside (bottom for floors) to inside. */
export type LayupLayer =
  | { kind: 'panel'; sku: SkuRef | LayupSkuToken; thickness_mm: Mm }
  /** Battens / studs at a spacing; optional insulation fill between them. */
  | { kind: 'members'; sku: SkuRef; thickness_mm: Mm; spacing_mm: Mm; fill?: SkuRef }
  | { kind: 'air'; thickness_mm: Mm }
  /**
   * The load-bearing structure (steel frame or container). Its members are
   * generated by the frame builder, not by the layup. Optional cavity fill.
   */
  | { kind: 'structure'; thickness_mm: Mm; fill?: SkuRef };

export interface Layup extends ItemBase {
  kind: 'layup';
  surface: 'wall' | 'roof' | 'floor' | 'partition';
  moduleTypes: ModuleType[];
  layers: LayupLayer[];
  /** true = counts as insulated for the equivalent sauna volume. */
  insulated: boolean;
}

// ------------------------------------------------------------ structure ---

export type FrameMemberRole =
  | 'base_perimeter'
  | 'base_crossmember'
  | 'column_corner'
  | 'column_grid'
  | 'top_perimeter'
  | 'roof_beam'
  | 'opening_reinforcement';

/** Data-driven frame topology for a module type (D-008). */
export interface FrameRecipe extends ItemBase {
  kind: 'frame_recipe';
  moduleType: ModuleType;
  members: Partial<Record<FrameMemberRole, { profile: SkuRef; maxSpacing_mm?: Mm }>>;
  /** Purchased lifting lug per top corner (custom frame). */
  liftingLug?: SkuRef;
  /** Welding / fabrication labour [h/kg of steel]. */
  welding_h_per_kg: number;
  /** Layups per surface. */
  layups: { wall: SkuRef; roof: SkuRef; floor: SkuRef; partition: SkuRef };
}

/** Purchased ISO container shell (tare + modifications are separate BOM lines). */
export interface ContainerShell extends ItemBase {
  kind: 'container';
  iso: '20HC';
  L_mm: Mm;
  W_mm: Mm;
  H_mm: Mm;
  tare_kg: Kg;
  /** COG of the empty container in module coordinates. */
  cog_mm: Vec3;
  cost: Czk;
  /** Corner post width; slots overlapping it cannot hold openings. */
  cornerPost_mm: Mm;
  /** Corrugated wall sheet mass per m² of wall (for cut-out deduction). */
  wallSheet_kg_per_m2: Kg;
  /** Cutting labour per m of cut. */
  cutting_h_per_m: number;
  /** End with the original doors and their mass (removed for a glass front). */
  doorEnd: 'E' | 'W';
  doors_kg: Kg;
}

/** Foundation system for a `Config.foundation` value. */
export interface FoundationSystem extends ItemBase {
  kind: 'foundation';
  type: Foundation;
  /** Purchased part at every support point (pad, ground screw). */
  pointSku: SkuRef;
  /** Max support spacing along the long sides (pads/screws) or skid spacing (beams). */
  maxSpacing_mm: Mm;
  /** Steel skid profile for 'beams'. */
  beamProfile?: SkuRef;
  /** Skid overhang beyond the base frame on each side. */
  beamOverhang_mm?: Mm;
}

// ------------------------------------------------------------- openings ---

export interface OpeningProduct extends ItemBase {
  kind: 'opening';
  type: OpeningType;
  /** Nominal product (rough opening) size. */
  width_mm: Mm;
  height_mm: Mm;
  /** Sill height above finished floor (0 for doors / glass fronts). */
  sill_mm: Mm;
  /** Number of slots the product occupies per grid. Missing grid = not allowed. */
  slots: Partial<Record<GridMm, number>>;
  /** Occupies the whole wall (all slots). */
  fullWall?: boolean;
  /** Door clear width (rule R04). */
  clearWidth_mm?: Mm;
  glassArea_m2: number;
  mass_kg: Kg;
  cost: Czk;
  /** Install labour [h/pc]. */
  install_h: number;
  /** Allowed module types (ISO may restrict). */
  moduleTypes: ModuleType[];
  asset?: string;
}

// ---------------------------------------------------------------- sauna ---

export interface Heater extends ItemBase {
  kind: 'heater';
  fuel: 'wood' | 'electric';
  power_kw: Kw;
  volume_min_m3: M3;
  volume_max_m3: M3;
  /** Safety clearances to combustible material, from heater casing. */
  clearance: { side_mm: Mm; front_mm: Mm; back_mm: Mm; top_mm: Mm };
  /** Casing: w along the wall, d away from the wall, h height. */
  size: { w_mm: Mm; d_mm: Mm; h_mm: Mm };
  /** Mass incl. stones. */
  mass_kg: Kg;
  stones_kg: Kg;
  minCabinHeight_mm: Mm;
  cost: Czk;
  install_h: number;
  electrical?: { voltage: 230 | 400; phases: 1 | 3 };
  flue?: {
    diameter_mm: Mm;
    /** Outlet centre relative to casing centre: [along wall, away from wall]. */
    offset_mm: readonly [Mm, Mm];
    /** Clearance of the insulated flue to combustibles. */
    clearanceCombustible_mm: Mm;
    /** Chimney set (purchased) added to BOM by rule R05. */
    chimneySku: SkuRef;
    /** Chimney height above the roof covering. */
    aboveRoof_mm: Mm;
  };
  asset?: string;
}

export interface BenchSystem extends ItemBase {
  kind: 'bench_system';
  /** Levels from the bottom; top_mm = bench top above finished floor. Config uses the top N. */
  levels: Array<{ top_mm: Mm; depth_mm: Mm }>;
  /** Bench board (panel role 'bench_board'). */
  board: SkuRef;
  /** Support timber SKU and max unsupported span (rule R09). */
  support: SkuRef;
  maxSpan_mm: Mm;
  defaultReturnLength_mm: Mm;
  assembly_h_per_m: number;
}

/** Purchased parts: lights, chimney sets, vents, lugs, pads, accessories. */
export interface PurchasedPart extends ItemBase {
  kind: 'purchased';
  category: 'light' | 'chimney' | 'vent' | 'electrical' | 'accessory' | 'foundation' | 'fixing' | 'lifting';
  mass_kg: Kg;
  cost: Czk;
  install_h: number;
  /** Removed for transport (chimney, railing…). */
  demountable: boolean;
  /** Nominal size for geometry [w, d, h]. */
  size_mm?: Vec3;
  asset?: string;
}

/** Terrace / overhang / stairs / railing systems; dimensions driven by config. */
export interface AttachmentSystem extends ItemBase {
  kind: 'attachment_system';
  type: 'terrace' | 'roof_overhang' | 'stairs' | 'railing';
  allowedDepths_mm?: Mm[];
  /** Mass and cost per m² of plan (terrace, overhang), per m (railing) or per pc (stairs). */
  basis: 'm2' | 'm' | 'ks';
  mass_kg_per_unit: Kg;
  cost_per_unit: Czk;
  install_h_per_unit: number;
  demountable: boolean;
  /** Geometry: deck / overhang thickness, railing or stairs height, stairs width. */
  thickness_mm?: Mm;
  height_mm?: Mm;
  width_mm?: Mm;
  /** Supported by its own posts (not loading module supports). */
  ownSupports: boolean;
  appearance: string;
}

/** Electrical sizing table row (rule R10). Informative only. */
export interface ElectricalRow {
  maxPower_kw: Kw;
  voltage: 230 | 400;
  breaker_A: number;
  cable: string; // e.g. 'CYKY-J 5×2,5'
  source: Source;
}

// ---------------------------------------------------------------- rates ---

export type PriceDisplayMode = 'hidden' | 'range' | 'exact';
export type PriceCategory = 'steel' | 'timber' | 'purchased' | 'labour' | 'transport' | 'crane';

export interface Rates {
  labour_per_h: Czk;
  transport: { per_km: Czk; flat: Czk; defaultDistance_km: number; oversizeSurcharge: Czk };
  /** Mobile crane, used when no vehicle with own crane can carry the module. */
  crane: { flat: Czk; per_h: Czk; defaultHours: number };
  /** Margin per category on top of cost. price = cost × (1 + margin). */
  margin: Record<PriceCategory, Ratio>;
  priceDisplay: PriceDisplayMode;
  /** Half-width of the shown range (0.10 = ±10 %). */
  priceRange: Ratio;
  /** Displayed prices are rounded to this step. */
  priceRounding_czk: Czk;
  /** Presentation only. */
  eurPerCzk: number;
}

// --------------------------------------------------------------- limits ---

/** Every rule threshold and physical coefficient lives here, with a source. */
export interface Limits {
  zoneMinLength_mm: Record<string, Sourced<Mm>>;
  /** Equivalent volume: +k m³ per m² of glass / uninsulated surface (R01). */
  eqVolumePerGlass_m3_per_m2: Sourced;
  eqVolumePerUninsulated_m3_per_m2: Sourced;
  /** Ceiling above the top bench (R03, warning). */
  topBenchToCeiling_mm: { min: Mm; max: Mm; source: Source };
  doorMinClearWidth_mm: Sourced<Mm>;
  /** Free passage depth inside the sauna in front of the door (R04). */
  doorClearDepth_mm: Sourced<Mm>;
  /** Opening wider than N slots → reinforcement frame (R07). */
  maxOpeningSlotsWithoutReinforcement: Record<ModuleType, Sourced<number>>;
  /** Min distance flue axis ↔ roof edge (eaves, gutter, overhang) (R05). */
  flueMinRoofEdgeDistance_mm: Sourced<Mm>;
  ventilation: {
    /** Supply grille centre above finished floor. */
    supplyHeight_mm: Sourced<Mm>;
    /** Exhaust grille centre below the ceiling. */
    exhaustBelowCeiling_mm: Sourced<Mm>;
    /** Exhaust distance from the room corner diagonally opposite the heater. */
    exhaustCornerOffset_mm: Sourced<Mm>;
    grilleSku: SkuRef;
    diameter_mm: Mm;
  };
  /** Lifting-point reaction spread warning (0.25 = 25 %). */
  liftReactionSpreadWarn: Sourced<Ratio>;
  transport: {
    maxWidth_mm: Sourced<Mm>;
    maxHeightOnVehicle_mm: Sourced<Mm>;
    /** Sorted by preference; first one that can carry the mass is used. */
    vehicles: Array<{ id: 'truck_hiab' | 'truck_crane'; maxMass_kg: Kg; deckHeight_mm: Mm; needsMobileCrane: boolean; name: I18nText; source: Source }>;
  };
  /** Gravity for kN outputs. */
  g_m_s2: number;
}

// -------------------------------------------------------------- catalog ---

/** Module options offered by the wizard (D-036). */
export interface ModuleOptions {
  custom_frame: {
    length_mm: { min: Mm; max: Mm; step: Mm };
    widths_mm: Mm[];
    /** Fixed height (Q3). */
    height_mm: Mm;
    grids_mm: GridMm[];
  };
  iso_20hc: { container: SkuRef; grids_mm: GridMm[] };
}

export interface Catalog {
  tenantId: string;
  version: string;
  /**
   * 'cost' = tenant catalog with purchase prices and margins (server, admin).
   * 'sell' = public catalog: every cost field already includes its margin and all
   * margins are 0, so `evaluate` gives the same prices without revealing costs (D-035).
   */
  pricing: 'cost' | 'sell';
  modules: ModuleOptions;
  steel: SteelMaterial[];
  profiles: SteelProfile[];
  timber: TimberSection[];
  panels: PanelMaterial[];
  layups: Layup[];
  frameRecipes: FrameRecipe[];
  containers: ContainerShell[];
  foundations: FoundationSystem[];
  openings: OpeningProduct[];
  heaters: Heater[];
  benchSystems: BenchSystem[];
  purchased: PurchasedPart[];
  attachmentSystems: AttachmentSystem[];
  electrical: ElectricalRow[];
  rules: RuleDef[];
  limits: Limits;
  rates: Rates;
}

export type CatalogItem =
  | SteelMaterial
  | SteelProfile
  | TimberSection
  | PanelMaterial
  | Layup
  | FrameRecipe
  | ContainerShell
  | FoundationSystem
  | OpeningProduct
  | Heater
  | BenchSystem
  | PurchasedPart
  | AttachmentSystem;

export type CatalogKind = CatalogItem['kind'];
export type CatalogItemOf<K extends CatalogKind> = Extract<CatalogItem, { kind: K }>;

/** Fast lookup built once per evaluation. `get` throws on unknown SKU. */
export interface CatalogIndex {
  catalog: Catalog;
  get<K extends CatalogKind>(kind: K, sku: SkuRef): CatalogItemOf<K>;
  find<K extends CatalogKind>(kind: K, sku: SkuRef): CatalogItemOf<K> | undefined;
  all<K extends CatalogKind>(kind: K): CatalogItemOf<K>[];
}

/** Public catalog (GET /tenants/:slug/public): sell prices, no costs or margins (D-035). */
export type PublicCatalog = Catalog & { pricing: 'sell' };
